### ISSUE TITLE
TODO before integration

### ISSUE THREAD

**Issue by vserret** [Qrlew/qrlew#83]
**Simple integration (we only reuse the schema)** 
- [x] Visitor for converting qrlew Schema to proto Schema : ½ - 1 day 

**Complete integration** 
- Conversion SqlParser::Query -> Relation  : 
- [x] HAVING, 
- [x] DISTINCT, (1 week)
- [x] COUNT(*), (2 days)
- [x] CAST
- [ ] TABLESAMPLE (1 day): ** Not supported by sqlparser**

- [ ] #234
- [x] String functions: upper, lower, concat, coalesce, trim, substring, substr, position, char_lengh, encode, decode, unhex, regexp_contains, regexp_extract, regexp_substr, regexp_replace (2 days)
- [x] Date functions: CURRENT_DATE | CURRENT_TIME | CURRENT_TIMESTAMP, EXTRACT, DAYNAME, FROM_UNIXTIME, UNIX_TIMESTAMP, DATE_FORMAT, QUARTER, DOW, DATETIME_DIFF, DATEPART, DATE (2 days)
- [x] Mathematical functions : abs, ceil, ceiling, floor, sign, sqrt, square, exp, ln, log, log10, log2, sin, cos, tan, asin, acos, atan, atanh, degrees, pi, random, rand, newid, round, power (2 days)
- [x] Boolean expressions
- [x] Truncate functions : trunc, truncate (1 day)
- [ ] Translator 
- [ ] #235
- [x]  Function for renaming tables
- [x] split quotes function
- [x] #232
- [ ] #233

- DP compilation: 
- [x] problem with when the peid is not a string (Could be resolved by implementing CAST)
- [x] DP estimators for : AVG, VARIANCE, STDDEV (2 days)
- [x] Automatic bounding ?
